@baseUrl = https://openrouter.ai/api/v1
@model = openai/gpt-oss-20b


POST {{baseUrl}}/chat/completions
Authorization: Bearer {{$dotenv OPENROUTER_API_KEY}}
Content-Type: application/json

{
  "model": "{{model}}",
  "messages": [
    {
      "role": "user",
      "content": "Explique brevemente o que é um token em IA."
    }
  ],
  "stream": true
}
